namespace Annihilation.Input
{
    public enum Button : byte
    {
        // Keyboard
        Escape = 0,
        Alpha1,
        Alpha2,
        Alpha3,
        Alpha4,
        Alpha5,
        Alpha6,
        Alpha7,
        Alpha8,
        Alpha9,
        Alpha0,
        Minus,
        Equals,
        Backspace,
        Tab,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        LeftBracket,
        RightBracket,
        Return,
        LeftControl,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        Semicolon,
        Apostrophe,
        Grave,
        LeftShift,
        Backslash,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        Comma,
        Period,
        Slash,
        RightShift,
        Multiply,
        LeftAlt,
        Space,
        Capslock,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        Numlock,
        ScrollLock,
        Numpad7,
        Numpad8,
        Numpad9,
        Subtract,
        Numpad4,
        Numpad5,
        Numpad6,
        Add,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad0,
        Decimal,
        F11,
        F12,
        NumpadEnter,
        NumpadPeriod,
        RightControl,
        Divide,
        PrintScreen,
        RightAlt,
        Pause,
        Home,
        Up,
        PageUp,
        Left,
        Right,
        End,
        Down,
        PageDown,
        Insert,
        Delete,
        LeftWindows,
        RightWindows,
        Application,

        KeyCount,

        // Gamepad
        DPadUp = KeyCount,
        DPadDown,
        DPadLeft,
        DPadRight,
        StartButton,
        BackButton,
        GuideButton,
        LeftStick,
        RightStick,
        LeftShoulder,
        RightShoulder,
        AButton,
        BButton,
        XButton,
        YButton,

        GamepadCount = (YButton - KeyCount) + 1,

        // Mouse
        MouseLeft = KeyCount + GamepadCount,
        MouseMiddle,
        MouseRight,
        MouseX1,
        MouseX2,

        MouseCount = (MouseX2 - GamepadCount) + 1,

        Count = KeyCount + GamepadCount + MouseCount
    }
}